# Generated by Django 2.1.7 on 2019-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lede',
            field=models.TextField(default='nullo'),
            preserve_default=False,
        ),
    ]
