# Generated by Django 2.1.7 on 2019-04-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_lede'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Rpost',
            field=models.BooleanField(default=False),
        ),
    ]
